
dep=-Wall -lglfw -lGL -lGLU -lglut -lGLEW -lX11 -lXxf86vm -lXrandr -lpthread -lXi -lrt -ldl -lXinerama -lXcursor

cherno:
	g++ draw_tri.cpp -o test ${dep} 

udemy:
	g++ draw_rect.cpp -o test ${dep}

youtube:
	g++ draw.cpp -o test ${dep}

clean:
	rm -f test