
run:
	g++ main.cpp -o test -Wall -lglfw -lGL -lGLU -lglut -lGLEW -lX11 -lXxf86vm -lXrandr -lpthread -lXi -lrt -ldl -lXinerama -lXcursor

glfw:
	g++ -o test glfw_test.cpp -lglfw -lGLU -lGL -lXrandr -lXxf86vm -lXi -lXinerama -lpthread  -lX11 -lrt -ldl

glew:
	g++ glew_test.cpp  -o test -Wall -lGL -lGLU -lglut -lGLEW -lX11 -lXxf86vm -lXrandr -lpthread -lXi -ldl -lXinerama -lXcursor

test:
	g++ test.cpp  -o test -Wall -lglfw -lGL -lGLU -lglut -lGLEW -lX11 -lXxf86vm -lXrandr -lpthread -lXi -lrt -ldl -lXinerama -lXcursor
